"""add traceable product and order imports

Revision ID: 0776318e56e3
Revises: 1a01867eb588
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0776318e56e3"
down_revision: str | None = "1a01867eb588"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mapping_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_channel", sa.String(length=20), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_mapping_templates_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mapping_templates")),
        sa.UniqueConstraint("owner_id", "name", name="uq_mapping_owner_name"),
    )
    op.create_index(
        op.f("ix_mapping_templates_owner_id"), "mapping_templates", ["owner_id"], unique=False
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source_channel", sa.String(length=20), nullable=False),
        sa.Column("data_identity", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=240), nullable=False),
        sa.Column("sheet_name", sa.String(length=120), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("exported_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("committed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("preview_revision", sa.Integer(), nullable=True),
        sa.Column("applied_revision", sa.Integer(), nullable=True),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.Column("raw_data", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("valid_rows", sa.Integer(), nullable=False),
        sa.Column("error_rows", sa.Integer(), nullable=False),
        sa.Column("new_rows", sa.Integer(), nullable=False),
        sa.Column("updated_rows", sa.Integer(), nullable=False),
        sa.Column("unchanged_rows", sa.Integer(), nullable=False),
        sa.Column("currencies", sa.JSON(), nullable=False),
        sa.Column("coverage_start", sa.String(length=40), nullable=True),
        sa.Column("coverage_end", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_import_batches_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_import_batches_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_owner_id"), "import_batches", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_import_batches_shop_id"), "import_batches", ["shop_id"], unique=False)
    op.create_table(
        "import_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("business_key", sa.String(length=64), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("corrections", sa.JSON(), nullable=False),
        sa.Column("normalized", sa.JSON(), nullable=False),
        sa.Column("previous", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["import_batches.id"], name=op.f("fk_import_rows_batch_id_import_batches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_rows")),
        sa.UniqueConstraint("batch_id", "row_number", name="uq_import_rows_batch_row"),
    )
    op.create_index(op.f("ix_import_rows_batch_id"), "import_rows", ["batch_id"], unique=False)
    op.create_index("ix_import_rows_key", "import_rows", ["business_key"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("line_id", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("sku", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("ordered_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("discount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("refund", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("fulfillment_status", sa.String(length=20), nullable=False),
        sa.Column("source_row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_order_lines_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["import_rows.id"],
            name=op.f("fk_order_lines_source_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_lines")),
        sa.UniqueConstraint("shop_id", "order_id", "line_id", name="uq_orders_shop_line"),
    )
    op.create_index(op.f("ix_order_lines_ordered_at"), "order_lines", ["ordered_at"], unique=False)
    op.create_index(op.f("ix_order_lines_shop_id"), "order_lines", ["shop_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("facts", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column("source_row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_products_shop_id_shops")),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["import_rows.id"],
            name=op.f("fk_products_source_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("shop_id", "sku", name="uq_products_shop_sku"),
    )
    op.create_index(op.f("ix_products_shop_id"), "products", ["shop_id"], unique=False)
    op.add_column(
        "shops", sa.Column("data_revision", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping the table also drops its FK-supporting indexes on MySQL.
    op.drop_column("shops", "data_revision")
    op.drop_table("products")
    op.drop_table("order_lines")
    op.drop_table("import_rows")
    op.drop_table("import_batches")
    op.drop_table("mapping_templates")
