"""add source-aware listing versions and approvals

Revision ID: 262449b655ea
Revises: a32132cebd28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "262449b655ea"
down_revision: str | None = "a32132cebd28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listing_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("product_key", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_status", sa.String(length=16), nullable=False),
        sa.Column("source_row_id", sa.Integer(), nullable=True),
        sa.Column("base_version_id", sa.Integer(), nullable=True),
        sa.Column("engine", sa.String(length=24), nullable=False),
        sa.Column("snapshot", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("decided_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_listing_versions_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_listing_versions_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["import_rows.id"],
            name=op.f("fk_listing_versions_source_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_versions")),
        sa.UniqueConstraint("owner_id", "request_key", name="uq_listing_request"),
        sa.UniqueConstraint("shop_id", "product_key", "number", name="uq_listing_number"),
    )
    op.create_index(
        op.f("ix_listing_versions_owner_id"), "listing_versions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_listing_versions_shop_id"), "listing_versions", ["shop_id"], unique=False
    )
    op.create_table(
        "listing_sources",
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_listing_sources_batch_id_import_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listing_versions.id"],
            name=op.f("fk_listing_sources_listing_id_listing_versions"),
        ),
        sa.PrimaryKeyConstraint("listing_id", "batch_id", name=op.f("pk_listing_sources")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("listing_sources")
    op.drop_table("listing_versions")
    # ### end Alembic commands ###
