"""bounded internal authorizations

Revision ID: 3b35be067576
Revises: 944381607c1c
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "3b35be067576"
down_revision: str | None = "944381607c1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "internal_authorizations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("origin_execution_id", sa.Integer(), nullable=False),
        sa.Column("skill", sa.String(length=40), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=False),
        sa.Column("used_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("source_valid_until", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("revoked_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_internal_authorizations_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_internal_authorizations_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_internal_authorizations")),
        sa.UniqueConstraint("owner_id", "request_id", name="uq_authorization_request"),
    )
    op.create_index(
        op.f("ix_internal_authorizations_owner_id"),
        "internal_authorizations",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_internal_authorizations_shop_id"),
        "internal_authorizations",
        ["shop_id"],
        unique=False,
    )
    op.create_table(
        "authorization_uses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("authorization_id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.Integer(), nullable=False),
        sa.Column("operation_run_id", sa.Integer(), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("reused_count", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("reverted_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.ForeignKeyConstraint(
            ["authorization_id"],
            ["internal_authorizations.id"],
            name=op.f("fk_authorization_uses_authorization_id_internal_authorizations"),
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_authorization_uses_execution_id_agent_executions"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_run_id"],
            ["operation_runs.id"],
            name=op.f("fk_authorization_uses_operation_run_id_operation_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authorization_uses")),
        sa.UniqueConstraint("execution_id", name="uq_authorization_execution"),
    )
    op.create_index(
        op.f("ix_authorization_uses_authorization_id"),
        "authorization_uses",
        ["authorization_id"],
        unique=False,
    )
    op.add_column("agent_executions", sa.Column("authorization_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_agent_executions_authorization_id_internal_authorizations"),
        "agent_executions",
        "internal_authorizations",
        ["authorization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_agent_executions_authorization_id_internal_authorizations"),
        "agent_executions",
        type_="foreignkey",
    )
    op.drop_column("agent_executions", "authorization_id")
    op.drop_table("authorization_uses")
    op.drop_table("internal_authorizations")
    # ### end Alembic commands ###
