"""add customer messages policies and source-aware reply drafts

Revision ID: 8d34d9c410a2
Revises: 262449b655ea
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "8d34d9c410a2"
down_revision: str | None = "262449b655ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "support_policies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("policy_key", sa.String(length=64), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("valid_from", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("valid_until", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("payload", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_support_policies_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_support_policies_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_policies")),
        sa.UniqueConstraint("owner_id", "request_key", name="uq_support_policy_request"),
        sa.UniqueConstraint("shop_id", "policy_key", "number", name="uq_support_policy_number"),
    )
    op.create_index(
        op.f("ix_support_policies_owner_id"), "support_policies", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_support_policies_shop_id"), "support_policies", ["shop_id"], unique=False
    )
    op.create_table(
        "customer_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("message_id", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("sent_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("order_id", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("source_row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_customer_messages_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["import_rows.id"],
            name=op.f("fk_customer_messages_source_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customer_messages")),
        sa.UniqueConstraint("shop_id", "channel", "message_id", name="uq_message_shop_channel_id"),
    )
    op.create_index(
        op.f("ix_customer_messages_shop_id"), "customer_messages", ["shop_id"], unique=False
    )
    op.create_table(
        "reply_drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("message_key", sa.String(length=64), nullable=False),
        sa.Column("source_row_id", sa.Integer(), nullable=True),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source_status", sa.String(length=16), nullable=False),
        sa.Column("engine", sa.String(length=24), nullable=False),
        sa.Column("snapshot", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_reply_drafts_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_reply_drafts_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["import_rows.id"],
            name=op.f("fk_reply_drafts_source_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reply_drafts")),
        sa.UniqueConstraint("owner_id", "request_key", name="uq_reply_request"),
    )
    op.create_index(op.f("ix_reply_drafts_owner_id"), "reply_drafts", ["owner_id"], unique=False)
    op.create_index(op.f("ix_reply_drafts_shop_id"), "reply_drafts", ["shop_id"], unique=False)
    op.create_table(
        "reply_policies",
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"], ["reply_drafts.id"], name=op.f("fk_reply_policies_draft_id_reply_drafts")
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["support_policies.id"],
            name=op.f("fk_reply_policies_policy_id_support_policies"),
        ),
        sa.PrimaryKeyConstraint("draft_id", "policy_id", name=op.f("pk_reply_policies")),
    )
    op.create_table(
        "reply_sources",
        sa.Column("draft_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_reply_sources_batch_id_import_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"], ["reply_drafts.id"], name=op.f("fk_reply_sources_draft_id_reply_drafts")
        ),
        sa.PrimaryKeyConstraint("draft_id", "batch_id", name=op.f("pk_reply_sources")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reply_sources")
    op.drop_table("reply_policies")
    op.drop_table("reply_drafts")
    op.drop_table("customer_messages")
    op.drop_table("support_policies")
    # ### end Alembic commands ###
