"""versioned business rules

Revision ID: 944381607c1c
Revises: a0188d77d6c6
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "944381607c1c"
down_revision: str | None = "a0188d77d6c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_rule_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("data_identity", sa.String(length=20), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("previous_id", sa.Integer(), nullable=False),
        sa.Column("restored_from_id", sa.Integer(), nullable=True),
        sa.Column("max_age_hours", sa.Integer(), nullable=False),
        sa.Column("min_quantity", sa.Integer(), nullable=False),
        sa.Column("max_margin_percent", sa.Numeric(precision=7, scale=2), nullable=False),
        sa.Column("advertising_daily_budget", sa.Numeric(precision=13, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.Column("basis", sa.String(length=500), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_business_rule_revisions_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_business_rule_revisions_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_rule_revisions")),
    )
    op.create_index(
        op.f("ix_business_rule_revisions_shop_id"),
        "business_rule_revisions",
        ["shop_id"],
        unique=False,
    )
    op.create_index(
        "ix_rule_scope",
        "business_rule_revisions",
        ["owner_id", "shop_id", "channel", "data_identity", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("business_rule_revisions")
    # ### end Alembic commands ###
