"""independent profit assumptions

Revision ID: a0188d77d6c6
Revises: e84b5e7e8dd1
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "a0188d77d6c6"
down_revision: str | None = "e84b5e7e8dd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profit_studies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("request_key", sa.String(length=36), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("data_identity", sa.String(length=24), nullable=False),
        sa.Column("rule_version", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_profit_studies_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_profit_studies_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profit_studies")),
        sa.UniqueConstraint("owner_id", "request_key", name="uq_profit_request"),
    )
    op.create_index(
        op.f("ix_profit_studies_owner_id"), "profit_studies", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_profit_studies_shop_id"), "profit_studies", ["shop_id"], unique=False)
    op.create_table(
        "profit_scenarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("study_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("price", sa.Numeric(precision=13, scale=4), nullable=False),
        sa.Column("purchase_cost", sa.Numeric(precision=13, scale=4), nullable=False),
        sa.Column("basis", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["study_id"],
            ["profit_studies.id"],
            name=op.f("fk_profit_scenarios_study_id_profit_studies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profit_scenarios")),
        sa.UniqueConstraint("study_id", "position", name="uq_profit_position"),
    )
    op.create_table(
        "profit_fees",
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Numeric(precision=13, scale=4), nullable=True),
        sa.Column("basis", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["profit_scenarios.id"],
            name=op.f("fk_profit_fees_scenario_id_profit_scenarios"),
        ),
        sa.PrimaryKeyConstraint("scenario_id", "kind", name=op.f("pk_profit_fees")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profit_fees")
    op.drop_table("profit_scenarios")
    op.drop_table("profit_studies")
    # ### end Alembic commands ###
