"""actual_expense_ledger

Revision ID: a269fe553f96
Revises: d6f920a41b85
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "a269fe553f96"
down_revision: str | None = "d6f920a41b85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("data_identity", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("evidence_key", sa.String(length=64), nullable=True),
        sa.Column("allocation", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_expenses_owner_id_users")
        ),
        sa.ForeignKeyConstraint(["shop_id"], ["shops.id"], name=op.f("fk_expenses_shop_id_shops")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint(
            "owner_id",
            "shop_id",
            "data_identity",
            "channel",
            "evidence_key",
            name="uq_expense_evidence",
        ),
    )
    op.create_index(op.f("ix_expenses_owner_id"), "expenses", ["owner_id"], unique=False)
    op.create_index(op.f("ix_expenses_shop_id"), "expenses", ["shop_id"], unique=False)
    op.create_table(
        "expense_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("occurred_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("snapshot", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["expense_id"], ["expenses.id"], name=op.f("fk_expense_revisions_expense_id_expenses")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_expense_revisions_owner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_revisions")),
        sa.UniqueConstraint("expense_id", "version", name="uq_expense_version"),
        sa.UniqueConstraint("owner_id", "request_id", name="uq_expense_request"),
    )
    op.create_index(
        op.f("ix_expense_revisions_expense_id"), "expense_revisions", ["expense_id"], unique=False
    )
    op.create_index(
        op.f("ix_expense_revisions_occurred_at"), "expense_revisions", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_expense_revisions_owner_id"), "expense_revisions", ["owner_id"], unique=False
    )
    op.create_table(
        "expense_sources",
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_expense_sources_batch_id_import_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["expense_id"], ["expenses.id"], name=op.f("fk_expense_sources_expense_id_expenses")
        ),
        sa.PrimaryKeyConstraint("expense_id", "batch_id", name=op.f("pk_expense_sources")),
    )
    op.create_index(
        op.f("ix_expense_sources_batch_id"), "expense_sources", ["batch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("expense_sources")
    op.drop_table("expense_revisions")
    op.drop_table("expenses")
