"""add saved analyses and source linked todos

Revision ID: a32132cebd28
Revises: 0776318e56e3
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "a32132cebd28"
down_revision: str | None = "0776318e56e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("snapshot", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_saved_analyses_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_saved_analyses_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_analyses")),
        sa.UniqueConstraint("owner_id", "request_key", name="uq_analysis_request"),
    )
    op.create_index(
        op.f("ix_saved_analyses_owner_id"), "saved_analyses", ["owner_id"], unique=False
    )
    op.create_index(op.f("ix_saved_analyses_shop_id"), "saved_analyses", ["shop_id"], unique=False)
    op.create_table(
        "analysis_sources",
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["saved_analyses.id"],
            name=op.f("fk_analysis_sources_analysis_id_saved_analyses"),
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_analysis_sources_batch_id_import_batches"),
        ),
        sa.PrimaryKeyConstraint("analysis_id", "batch_id", name=op.f("pk_analysis_sources")),
    )
    op.create_table(
        "analysis_todos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["saved_analyses.id"],
            name=op.f("fk_analysis_todos_analysis_id_saved_analyses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_todos")),
        sa.UniqueConstraint("analysis_id", name=op.f("uq_analysis_todos_analysis_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis_todos")
    op.drop_table("analysis_sources")
    op.drop_table("saved_analyses")
    # ### end Alembic commands ###
