"""persistent operation schedules and notifications

Revision ID: a364d8b4b6bf
Revises: 86df84dc129a
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "a364d8b4b6bf"
down_revision: str | None = "86df84dc129a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("next_run_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_operation_schedules_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_operation_schedules_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_schedules")),
        sa.UniqueConstraint("owner_id", "request_id", name="uq_schedule_request"),
    )
    op.create_index(
        op.f("ix_operation_schedules_owner_id"), "operation_schedules", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_operation_schedules_shop_id"), "operation_schedules", ["shop_id"], unique=False
    )
    op.create_index(
        "ix_schedule_due", "operation_schedules", ["status", "next_run_at"], unique=False
    )
    op.create_table(
        "schedule_occurrences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("schedule_version", sa.Integer(), nullable=False),
        sa.Column("slot_key", sa.String(length=64), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("scheduled_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("coalesced_from", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("execution_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("notify_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("read_at", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_schedule_occurrences_execution_id_agent_executions"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_schedule_occurrences_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["operation_schedules.id"],
            name=op.f("fk_schedule_occurrences_schedule_id_operation_schedules"),
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_schedule_occurrences_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_occurrences")),
        sa.UniqueConstraint("schedule_id", "slot_key", name="uq_schedule_slot"),
    )
    op.create_index(
        op.f("ix_schedule_occurrences_owner_id"), "schedule_occurrences", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_schedule_occurrences_schedule_id"),
        "schedule_occurrences",
        ["schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_occurrences_shop_id"), "schedule_occurrences", ["shop_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL requires FK-supporting indexes until their table/constraint is removed.
    op.drop_table("schedule_occurrences")
    op.drop_table("operation_schedules")
