"""channel_statement_lines

Revision ID: d32312391696
Revises: a269fe553f96
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "d32312391696"
down_revision: str | None = "a269fe553f96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for name in ("created_at", "expires_at", "committed_at"):
        op.alter_column(
            "import_batches",
            name,
            existing_type=sa.DateTime(),
            type_=mysql.DATETIME(fsp=6),
            existing_nullable=name == "committed_at",
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statement_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("data_identity", sa.String(length=20), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("statement_id", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("line_id", sa.String(length=120, collation="utf8mb4_bin"), nullable=False),
        sa.Column("entry_type", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("evidence_ref", sa.String(length=120), nullable=False),
        sa.Column("fee_name", sa.String(length=120), nullable=False),
        sa.Column("settlement_id", sa.String(length=120), nullable=False),
        sa.Column("order_id", sa.String(length=120), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=False),
        sa.Column("source_row_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_statement_lines_shop_id_shops")
        ),
        sa.ForeignKeyConstraint(
            ["source_row_id"],
            ["import_rows.id"],
            name=op.f("fk_statement_lines_source_row_id_import_rows"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statement_lines")),
        sa.UniqueConstraint(
            "shop_id",
            "data_identity",
            "channel",
            "statement_id",
            "line_id",
            name="uq_statement_scope_line",
        ),
    )
    op.create_index(
        op.f("ix_statement_lines_shop_id"), "statement_lines", ["shop_id"], unique=False
    )
    op.create_index(
        "ix_statement_scope_time",
        "statement_lines",
        ["shop_id", "data_identity", "channel", "occurred_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for name in ("created_at", "expires_at", "committed_at"):
        op.alter_column(
            "import_batches",
            name,
            existing_type=mysql.DATETIME(fsp=6),
            type_=sa.DateTime(),
            existing_nullable=name == "committed_at",
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_statement_scope_time", table_name="statement_lines")
    op.drop_index(op.f("ix_statement_lines_shop_id"), table_name="statement_lines")
    op.drop_table("statement_lines")
    # ### end Alembic commands ###
