"""controlled_agent_execution

Revision ID: e84b5e7e8dd1
Revises: c37d9218a640
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "e84b5e7e8dd1"
down_revision: str | None = "c37d9218a640"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("shop_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("template", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("next_node", sa.String(length=32), nullable=False),
        sa.Column("source_status", sa.String(length=16), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("input", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("result", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("steps_used", sa.Integer(), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("spent_usd", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("reserved_usd", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("model_status", sa.String(length=24), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("lease_until", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("valid_until", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_agent_executions_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["shop_id"], ["shops.id"], name=op.f("fk_agent_executions_shop_id_shops")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_executions")),
        sa.UniqueConstraint("owner_id", "request_id", name="uq_agent_request"),
    )
    op.create_index(
        op.f("ix_agent_executions_owner_id"), "agent_executions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_executions_shop_id"), "agent_executions", ["shop_id"], unique=False
    )
    op.create_table(
        "agent_policy_sources",
        sa.Column("execution_id", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_agent_policy_sources_execution_id_agent_executions"),
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["support_policies.id"],
            name=op.f("fk_agent_policy_sources_policy_id_support_policies"),
        ),
        sa.PrimaryKeyConstraint("execution_id", "policy_id", name=op.f("pk_agent_policy_sources")),
    )
    op.create_table(
        "agent_sources",
        sa.Column("execution_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
            name=op.f("fk_agent_sources_batch_id_import_batches"),
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_agent_sources_execution_id_agent_executions"),
        ),
        sa.PrimaryKeyConstraint("execution_id", "batch_id", name=op.f("pk_agent_sources")),
    )
    op.create_table(
        "agent_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("execution_id", sa.Integer(), nullable=False),
        sa.Column("node", sa.String(length=32), nullable=False),
        sa.Column("skill", sa.String(length=40), nullable=False),
        sa.Column("skill_version", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=80), nullable=False),
        sa.Column("next_node", sa.String(length=32), nullable=False),
        sa.Column("input", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("output", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["agent_executions.id"],
            name=op.f("fk_agent_steps_execution_id_agent_executions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_steps")),
    )
    op.create_index(
        op.f("ix_agent_steps_execution_id"), "agent_steps", ["execution_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_steps")
    op.drop_table("agent_sources")
    op.drop_table("agent_policy_sources")
    op.drop_table("agent_executions")
    # ### end Alembic commands ###
